server:
  port: 3344

spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Yhongwu/microservicecloud-config.git   # github…œµƒ≤÷ø‚µÿ÷∑


