# 端口
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.howard.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml        # mapper映射文件
spring:
  application:
    name: microservicecloud-dept                      # 服务名 注册进eureka后将显示该名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        # mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb01        # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                     # 数据库连接池的最小维持连接数
      initial-size: 5                                 # 初始化连接数
      max-total: 5                                    # 最大连接数
      max-wait-millis: 2000                           # 等待连接获取的最大超时时间


#客户端注册进eureka服务列表内
eureka:
  client:
    service-url:
      # 链接符合eureka-7001中eureka服务端的defaultZone 单机配置
      # defaultZone: http://localhost:7001/eureka
      # 集群配置
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001-hystrix       # eureka的主页面服务注册进去时status的访问路径显示名
    prefer-ip-address: true                       # 鼠标移到status下的访问路径时，浏览器右下角访问路径可以显示IP地址

info:
  app.name: hongwu-microservicecloud
  company.name: www.hongwu.com
  # 以@开头和结尾的可以去读取资源文件 即类似动态不写死 以$会与spring的$起冲突不生效
  build.artifactId: @project.artifactId@
  build.version: @project.version@