server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true  #访问路径鼠标移上去显示ip

info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@

# 测试18
zuul:
  # 让原服务名的路径无法访问
  # ignored-services: microservicecloud-dept
  # 也可通过如下让多个为真正的服务名无法访问
  ignored-services: "*"
  # 设置统一公共前缀
  prefix: /howard
  # 代理微服务路径名为mydept
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
